FROM node as buildstep
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build -- --configuration=production

FROM nginx
COPY --from=buildstep /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=buildstep /app/dist/out /usr/share/nginx/html
EXPOSE 80
